const fs = require('node:fs')
const path = require('node:path')
const test = require('node:test')
const assert = require('node:assert/strict')

const home = fs.readFileSync(path.join(process.cwd(), 'app/[username]/today-conversation-shell.tsx'), 'utf8')
const voice = fs.readFileSync(path.join(process.cwd(), 'app/[username]/progression-voice-answer-recorder.tsx'), 'utf8')

test('progression follow-up composer uses recorded voice answers and keyboard-safe mobile layout', () => {
  assert.match(home, /BALAS PERTANYAAN SYSTEM/)
  assert.match(home, /ProgressionVoiceAnswerRecorder/)
  assert.match(home, /fontSize: 16/)
  assert.match(home, /minHeight: 44/)
  assert.doesNotMatch(home, /webkitSpeechRecognition/)
  assert.doesNotMatch(home, /data-sticky-chat-composer[\s\S]{0,220}position: 'fixed'/)
  assert.match(voice, /MediaRecorder/)
  assert.match(voice, /ingestVoiceKnowledge/)
  assert.match(voice, /answerProgressionQuestionWithVoice/)
  assert.match(voice, /KIRIM SUARA →/)
})
