/* eslint-disable @typescript-eslint/no-require-imports */
const test = require('node:test')
const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')

function read(relative) {
  return fs.readFileSync(path.join(process.cwd(), relative), 'utf8')
}

test('migration creates four-layer intelligence persistence and owner-scoped RLS', () => {
  const sql = read('supabase/sql/add_progression_intelligence_loop.sql')
  assert.match(sql, /create table if not exists public\.progression_maps/)
  assert.match(sql, /create table if not exists public\.player_response_models/)
  assert.match(sql, /create table if not exists public\.progression_targets/)
  assert.match(sql, /create table if not exists public\.quest_response_events/)
  assert.match(sql, /alter table public\.progression_maps enable row level security/)
  assert.match(sql, /progression_maps_select_own/)
  assert.match(sql, /player_response_models_select_own/)
  assert.match(sql, /progression_targets_select_own/)
  assert.match(sql, /quest_response_events_select_own/)
  assert.match(sql, /add column if not exists strategic_chain jsonb/)
  assert.match(sql, /add column if not exists execution_contract jsonb/)
})

test('learning sync is idempotent and no-quest reason is explicit', () => {
  const sql = read('supabase/sql/fix_progression_intelligence_no_quest_sync.sql')
  assert.match(sql, /where public\.quest_response_events\.outcome is distinct from excluded\.outcome/)
  assert.match(sql, /reviewed_at=null/)
  assert.match(sql, /p_no_quest_reason text/)
  assert.match(sql, /No-quest plan requires a reason/)
  assert.doesNotMatch(sql, /requires no_intervention target/)
})

test('quest result capture separates compliance storage from effectiveness learning', () => {
  const sql = read('supabase/sql/harden_progression_quest_results.sql')
  assert.match(sql, /record_daily_quest_result/)
  assert.match(sql, /'completed','partial','skipped','failed'/)
  assert.match(sql, /insert into public\.quest_results/)
  assert.match(sql, /delete from public\.quest_response_events/)
  assert.match(sql, /insert into public\.ai_inference_jobs/)
  assert.doesNotMatch(sql, /effectiveness='strong'/)
})

test('worker runs response learning and strategic target before new quest generation', () => {
  const worker = read('workers/chatgpt-consumer/worker-v2.mjs')
  const syncAt = worker.indexOf('responseEventsSynced = await progressionStore.syncQuestResponseEvents')
  const reviewAt = worker.indexOf('const reviews = await reviewQuestResponses')
  const responseModelAt = worker.indexOf('const responseModel = await refreshPlayerResponseModel')
  const targetAt = worker.indexOf('const target = await chooseProgressionTarget')
  const generationAt = worker.indexOf('generated = await generateDailyQuestsWithIntelligence')
  assert.ok(syncAt > 0)
  assert.ok(reviewAt > syncAt)
  assert.ok(responseModelAt > reviewAt)
  assert.ok(targetAt > responseModelAt)
  assert.ok(generationAt > targetAt)
  assert.match(worker, /hasFinalizedPlanForDate/)
  assert.match(worker, /source: 'no_quest'/)
  assert.match(worker, /noQuest: generated\.source === 'no_quest'/)
  assert.doesNotMatch(worker, /generateDailyQuests\(/)
})

test('Today recognizes a finalized zero-quest plan and exposes causal execution details', () => {
  const page = read('app/[username]/page.tsx')
  assert.match(page, /dailyPlanReady = questReady \|\| Boolean\(dailyPlan\?\.finalized\)/)
  assert.match(page, /SYSTEM DECISION · NO QUEST NEEDED/)
  assert.match(page, /TODAY’S PROGRESSION TARGET/)
  assert.match(page, /WHY ·/)
  assert.match(page, /DONE WHEN ·/)
  assert.match(page, /DOSE ·/)
  assert.match(page, /record_daily_quest_result/)
  assert.match(page, /\(\['partial', 'skipped', 'failed'\] as const\)/)
  assert.match(page, /outcome\.toUpperCase\(\)/)
  assert.doesNotMatch(page, /No Daily Quest was persisted for today\./)
})
